services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Mindy\Template\Library\LibraryInterface:
            public: true
            tags: ['template.library']

    Mindy\Bundle\SocialAuthBundle\:
        resource: '../../*'
        exclude: '../../{Tests,Provider,Migrations,Model,vendor}'

    Mindy\Bundle\SocialAuthBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
