services:
    Mindy\Bundle\SocialBundle\Provider\Facebook\Facebook:
        arguments:
            -
                clientId: '%mindy.social.provider.facebook.client_id%'
                clientSecret: '%mindy.social.provider.facebook.client_secret%'
                scope: '%mindy.social.provider.facebook.scope%'
                graphApiVersion: '%mindy.social.provider.facebook.graph_api_version%'
        tags:
            - { name: social.provider, provider: facebook }
